<?php 

/**
 * Main month view template file
 * 
 */

$thisMonth = $this->calendar->getStartTime();
$nextMonth = strtotime('+1 month', $thisMonth);
$prevMonth = strtotime('-1 month', $thisMonth);

$monthTitle = date("F Y", $thisMonth);
$this->headTitle($monthTitle);

?>

<script type="text/javascript">
  dojo.require("dijit.Dialog");
  dojo.require("dijit.form.TextBox");  
  dojo.require("dijit.form.TimeTextBox");
  dojo.require("dijit.form.Button");
  dojo.require("dijit.form.DateTextBox");
  dojo.require("dijit.form.FilteringSelect");

  dojo.addOnLoad(function() {
	  dojo.parser.parse();
  });
</script>


<div class="calendar">
    <h2><?php echo $monthTitle; ?></h2>
    <div class="calendar-toolbar">
        <a href="<?php echo $this->baseUrl . '/month/' . date("Y/m", $prevMonth) ?>">&laquo; prev</a>
        <a href="<?php echo $this->baseUrl . '/month/' . date("Y/m", $_SERVER['REQUEST_TIME']) ?>">today</a>
        <a href="<?php echo $this->baseUrl . '/month/' . date("Y/m", $nextMonth) ?>">next &raquo;</a>
        <form method="get">
            go to: <input type="text" name="jumpto" />
        </form>
    </div>
    <?php echo $this->renderMonthCalendar($this->calendar); ?>
</div>