<?php

/**
 * SimpleCal - main layout file
 * 
 * @author Shahar Evron, <shahar.e@zend.com>
 */

echo '<?xml version="1.0" encoding="UTF-8" ?>';
?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <?php echo $this->headTitle(); ?> 
    <?php echo $this->headLink(); ?> 
    <?php echo $this->headScript(); ?> 
</head>

<body>
    <div id="page-title">
        <h1>My Simple Calendar</h1>
    </div>
    
    <div id="page-content">
        <?php echo $this->layout()->content ?>
    </div>
    
    <div id="page-footer">
        <p>
            Powered by SimpleCal 0.1, Zend Framework and Zend Server
        </p>
        <p>
            application design is &copy; 2009 Zend Technologies Ltd
        </p>    
    </div> 
</body>

</html>