<?php

/**
 * SimpleCal - main layout file
 * 
 * @author Shahar Evron, <shahar.e@zend.com>
 */

$this->headTitle('My Calendar');
echo '<?xml version="1.0" encoding="UTF-8" ?>' . "\n" . $this->doctype();
?>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <?php echo $this->headTitle(); ?> 
    <?php echo $this->headLink(); ?> 
    <?php if ($this->dojo()->isEnabled()) {
        $this->dojo()->setCdnBase(Zend_Dojo::CDN_BASE_GOOGLE)
                     ->addStyleSheetModule('dijit.themes.tundra');
        echo $this->dojo();
    } ?> 
    <?php echo $this->headScript() ?>
</head>

<body>
    <div id="page-title">
        <h1>My Simple Calendar</h1>
        <div class="title-toolbox">
            timezone: <?php echo date_default_timezone_get() ?>
            <a href="<?php echo $this->baseUrl ?>/timezone">[ change... ]</a>
        </div>
    </div>
    
    <div id="page-content">
        <?php echo $this->layout()->content ?>
    </div>
    
    <div id="page-footer">
        <p>
            Powered by SimpleCal 0.1, Zend Framework and Zend Server
        </p>
        <p>
            application design is &copy; 2009 Zend Technologies Ltd
        </p>    
    </div>
    <?php echo $this->inlineScript(); ?> 
</body>

</html>